const c=document.querySelector('#canvas'),ctx=c.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id);
const defaults={branches:6,depth:6,spread:58,scale:66,twist:14,speed:34,width:11,color:'#f5f5f5',glow:true};let s={...defaults},playing=true,t=0,rot=0,zoom=1,drag=false,lastX=0,lastDist=0,lastTap=0,frames=0,lastFps=performance.now();
const ids=['branches','depth','spread','scale','twist','speed','width'];
function sync(){ids.forEach(id=>{$(id).value=s[id];$(id+'Out').value=id==='scale'?s[id]+'%':id==='spread'||id==='twist'?s[id]+'°':s[id]});$('color').value=s.color;$('glow').checked=s.glow}
ids.forEach(id=>$(id).addEventListener('input',e=>{s[id]=+e.target.value;sync()}));$('color').oninput=e=>s.color=e.target.value;$('glow').onchange=e=>s.glow=e.target.checked;
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play'};$('reset').onclick=()=>{s={...defaults};rot=0;zoom=1;sync()};$('random').onclick=()=>{s.branches=2+Math.floor(Math.random()*9);s.depth=4+Math.floor(Math.random()*4);s.spread=20+Math.floor(Math.random()*130);s.scale=52+Math.floor(Math.random()*24);s.twist=-55+Math.floor(Math.random()*110);s.speed=10+Math.floor(Math.random()*70);s.width=6+Math.floor(Math.random()*16);sync()};
$('fullscreen').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};
function resize(){const d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function branch(len,depth,angle){if(depth<=0||len<1)return;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-len);ctx.stroke();ctx.translate(0,-len);const spread=s.spread*Math.PI/180,tw=s.twist*Math.PI/180,sc=s.scale/100;for(let i=0;i<s.branches;i++){const a=(i-(s.branches-1)/2)*(spread/Math.max(1,s.branches-1))+tw+Math.sin(t*.9+depth+i)*.035;ctx.save();ctx.rotate(a);branch(len*sc,depth-1,angle+a);ctx.restore()}}
function draw(now){requestAnimationFrame(draw);if(playing)t+=.008*(s.speed/30);ctx.fillStyle='#050505';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth/2,innerHeight*.46);ctx.scale(zoom,zoom);ctx.rotate(rot+t*.07);ctx.strokeStyle=s.color;ctx.lineWidth=s.width/10;ctx.lineCap='round';ctx.globalAlpha=.9;if(s.glow){ctx.shadowColor=s.color;ctx.shadowBlur=10}const base=Math.min(innerWidth,innerHeight)*.18;for(let i=0;i<s.branches;i++){ctx.save();ctx.rotate(i*Math.PI*2/s.branches);branch(base,s.depth,0);ctx.restore()}ctx.restore();frames++;if(now-lastFps>700){$('fps').textContent=Math.round(frames*1000/(now-lastFps))+' FPS';frames=0;lastFps=now}}
function dist(ts){return Math.hypot(ts[0].clientX-ts[1].clientX,ts[0].clientY-ts[1].clientY)}
c.addEventListener('touchstart',e=>{if(e.touches.length===1){drag=true;lastX=e.touches[0].clientX;const n=Date.now();if(n-lastTap<300){rot=0;zoom=1}lastTap=n}else if(e.touches.length===2){lastDist=dist(e.touches)}},{passive:false});c.addEventListener('touchmove',e=>{e.preventDefault();if(e.touches.length===1&&drag){const x=e.touches[0].clientX;rot+=(x-lastX)*.008;lastX=x}else if(e.touches.length===2){const d=dist(e.touches);zoom=Math.max(.45,Math.min(3,zoom*d/lastDist));lastDist=d}},{passive:false});c.addEventListener('touchend',()=>drag=false);c.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){drag=true;lastX=e.clientX}});addEventListener('pointermove',e=>{if(drag&&e.pointerType==='mouse'){rot+=(e.clientX-lastX)*.008;lastX=e.clientX}});addEventListener('pointerup',()=>drag=false);c.addEventListener('wheel',e=>{zoom=Math.max(.45,Math.min(3,zoom*(e.deltaY>0?.92:1.08)))},{passive:true});sync();requestAnimationFrame(draw);
